In [1]:
## Rule-Attention Integrated Network

In [2]:
import sys
sys.path.append('../')
from rules.metric import *

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "3"
from elmoformanylangs import Embedder, CNEmbedder

In [2]:
e = Embedder('/data/wujipeng/embedding/ELMo/zhs.model/')
c = CNEmbedder('/data/wujipeng/embedding/ELMo/zhs.model/')

2019-03-19 16:43:36,318 INFO: char embedding size: 6169
2019-03-19 16:43:36,666 INFO: word embedding size: 71222
2019-03-19 16:44:03,982 INFO: Model(
  (token_embedder): ConvTokenEmbedder(
    (word_emb_layer): EmbeddingLayer(
      (embedding): Embedding(71222, 100, padding_idx=3)
    )
    (char_emb_layer): EmbeddingLayer(
      (embedding): Embedding(6169, 50, padding_idx=6166)
    )
    (convolutions): ModuleList(
      (0): Conv1d(50, 32, kernel_size=(1,), stride=(1,))
      (1): Conv1d(50, 32, kernel_size=(2,), stride=(1,))
      (2): Conv1d(50, 64, kernel_size=(3,), stride=(1,))
      (3): Conv1d(50, 128, kernel_size=(4,), stride=(1,))
      (4): Conv1d(50, 256, kernel_size=(5,), stride=(1,))
      (5): Conv1d(50, 512, kernel_size=(6,), stride=(1,))
      (6): Conv1d(50, 1024, kernel_size=(7,), stride=(1,))
    )
    (highways): Highway(
      (_layers): ModuleList(
        (0): Linear(in_features=2048, out_features=4096, bias=True)
        (1): Linear(in_features=2048, out_feat

In [111]:
sents = [['我', '爱', '北京', '天安门', '<pad>', '<pad>', '<pad>'], ['天安门', '前', '坦克', '冲']]

In [115]:
embed = e.sents2elmo(sents, 0)
embed

2019-03-19 16:42:24,230 INFO: 1 batches, avg len: 7.5


[array([[ 0.13360134,  0.05176929,  0.5049831 , ...,  0.13314141,
          0.49482244,  0.07487966],
        [ 0.3522513 ,  0.3439607 ,  0.5728881 , ...,  0.01634456,
         -0.20670648,  0.20261244],
        [-0.0674175 ,  0.37687594,  0.43225384, ...,  0.05993162,
          0.11410472, -0.69082123],
        ...,
        [-0.12381966,  0.866776  ,  0.2685415 , ..., -0.09284096,
         -0.5579087 , -0.7215217 ],
        [-0.12381966,  0.866776  ,  0.2685415 , ..., -0.09284096,
         -0.5579087 , -0.7215217 ],
        [-0.12381966,  0.866776  ,  0.2685415 , ..., -0.09284096,
         -0.5579087 , -0.7215217 ]], dtype=float32),
 array([[ 0.24336524,  0.5533514 ,  0.4132815 , ...,  0.06044367,
          0.18921544, -1.0009525 ],
        [ 0.0777937 , -0.16826117,  0.27988923, ...,  0.03884932,
          0.5104188 , -0.03183861],
        [ 0.16183703, -0.71312773,  0.00263081, ..., -0.46667844,
          0.9072407 , -0.33262712],
        [ 0.5971473 ,  0.7700659 ,  0.4508716 , ...,

In [114]:
cmbed = c.sents2elmo(sents, 0)
cmbed

tensor([[[ 0.1336,  0.0518,  0.5050,  ...,  0.1331,  0.4948,  0.0749],
         [ 0.3523,  0.3440,  0.5729,  ...,  0.0163, -0.2067,  0.2026],
         [-0.0674,  0.3769,  0.4323,  ...,  0.0599,  0.1141, -0.6908],
         ...,
         [-0.1238,  0.8668,  0.2685,  ..., -0.0928, -0.5579, -0.7215],
         [-0.1238,  0.8668,  0.2685,  ..., -0.0928, -0.5579, -0.7215],
         [-0.1238,  0.8668,  0.2685,  ..., -0.0928, -0.5579, -0.7215]],

        [[ 0.2434,  0.5534,  0.4133,  ...,  0.0604,  0.1892, -1.0010],
         [ 0.0778, -0.1683,  0.2799,  ...,  0.0388,  0.5104, -0.0318],
         [ 0.1618, -0.7131,  0.0026,  ..., -0.4667,  0.9072, -0.3326],
         ...,
         [-0.4240, -0.8640, -0.5982,  ..., -0.3724,  1.3855, -1.1962],
         [-0.1227,  0.2681,  0.2483,  ..., -0.0263, -0.0282, -0.1805],
         [-0.1227,  0.2681,  0.2483,  ..., -0.0263, -0.0282, -0.1805]]])

In [93]:
embed[0].shape, embed[1].shape

((6, 1024), (5, 1024))

In [92]:
cmbed.size()

torch.Size([2, 6, 1024])

In [86]:
c.sents2elmo(sents, -2).transpose(0, 1)

tensor([[[[ 1.3360e-01,  5.1769e-02,  5.0498e-01,  ...,  1.3314e-01,
            4.9482e-01,  7.4880e-02],
          [ 3.5225e-01,  3.4396e-01,  5.7289e-01,  ...,  1.6345e-02,
           -2.0671e-01,  2.0261e-01],
          [-6.7418e-02,  3.7688e-01,  4.3225e-01,  ...,  5.9932e-02,
            1.1410e-01, -6.9082e-01],
          [ 2.4337e-01,  5.5335e-01,  4.1328e-01,  ...,  6.0444e-02,
            1.8922e-01, -1.0010e+00],
          [-1.2382e-01,  8.6678e-01,  2.6854e-01,  ..., -9.2841e-02,
           -5.5791e-01, -7.2152e-01],
          [-1.2382e-01,  8.6678e-01,  2.6854e-01,  ..., -9.2841e-02,
           -5.5791e-01, -7.2152e-01]],

         [[ 2.4337e-01,  5.5335e-01,  4.1328e-01,  ...,  6.0444e-02,
            1.8922e-01, -1.0010e+00],
          [ 7.7794e-02, -1.6826e-01,  2.7989e-01,  ...,  3.8849e-02,
            5.1042e-01, -3.1839e-02],
          [ 1.6184e-01, -7.1313e-01,  2.6308e-03,  ..., -4.6668e-01,
            9.0724e-01, -3.3263e-01],
          [ 5.9715e-01,  7.7007e-01